# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20160309_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='height',
            field=models.IntegerField(default=352),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='width',
            field=models.IntegerField(default=640),
            preserve_default=False,
        ),
    ]
