# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20160315_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='img',
            field=models.ImageField(default='1.gif', upload_to='../media/'),
            preserve_default=False,
        ),
    ]
