# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_camera_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'permissions': (('camera_access', 'Camera access'),)},
        ),
    ]
