# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter', '0006_auto_20160318_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='user',
        ),
        migrations.AddField(
            model_name='camera',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
