# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0008_auto_20160326_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_s', models.DateTimeField(help_text='Время начала')),
                ('time_e', models.DateTimeField(help_text='Время завершения')),
                ('interval_length', models.IntegerField(choices=[(300, '5 минут'), (600, '10 минут'), (1800, '30 минут'), (3600, '1 час')], default=600, help_text='Время интервалов')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Camera')),
            ],
        ),
    ]
