# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0009_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('options', models.ManyToManyField(to='counter.ZoneOption')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counter.OptionsSet'),
        ),
    ]
