# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0012_optionsset_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='norm_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
