# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0013_direction_norm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='status',
            field=models.CharField(choices=[('done', 'завершено'), ('waiting', 'ожидает'), ('inprocess', 'в процессе')], default='waiting', max_length=200),
        ),
    ]
