# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0014_timetable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsset',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='counter.Camera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='options',
            field=models.ForeignKey(help_text='Набор настроек', null=True, on_delete=django.db.models.deletion.CASCADE, to='counter.OptionsSet'),
        ),
    ]
