# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0016_auto_20160329_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneoption',
            name='blur',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='zoneoption',
            name='max_object_area',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='zoneoption',
            name='min_object_area',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='zoneoption',
            name='rad',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='zoneoption',
            name='sensitivity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='zoneoption',
            name='set_rad',
            field=models.IntegerField(default=10),
        ),
    ]
