# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0017_auto_20160330_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='camera',
            name='width',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='height',
            field=models.PositiveIntegerField(help_text='Высота'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='width',
            field=models.PositiveIntegerField(help_text='Ширина'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='x1',
            field=models.PositiveIntegerField(help_text='x1'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='x2',
            field=models.PositiveIntegerField(help_text='x2'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='x3',
            field=models.PositiveIntegerField(help_text='x3'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='x4',
            field=models.PositiveIntegerField(help_text='x4'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='y1',
            field=models.PositiveIntegerField(help_text='y1'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='y2',
            field=models.PositiveIntegerField(help_text='y2'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='y3',
            field=models.PositiveIntegerField(help_text='y3'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='y4',
            field=models.PositiveIntegerField(help_text='y4'),
        ),
        migrations.AlterField(
            model_name='zoneoption',
            name='blur',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='zoneoption',
            name='rad',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='zoneoption',
            name='sensitivity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='zoneoption',
            name='set_rad',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
