# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0018_auto_20160330_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoneoption',
            name='max_object_area',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='zoneoption',
            name='min_object_area',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
