# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter', '0021_auto_20160404_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='group',
            field=models.ManyToManyField(to='counter.Company'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Company'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.CUser'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Company'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.CUser'),
        ),
    ]
