# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0024_auto_20160404_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
