# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0026_auto_20160404_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={},
        ),
        migrations.AddField(
            model_name='timetable',
            name='date_s',
            field=models.DateField(default='2016-04-11', help_text='Дата начала'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('sunday', 'Суббота'), ('saturday', 'Воскресенье')], max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='options',
            field=models.ManyToManyField(help_text='Набор настроек', to='counter.ZoneOption'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_e',
            field=models.TimeField(default='00:00', help_text='Время конца'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_s',
            field=models.TimeField(default='00:00', help_text='Время начала'),
        ),
    ]
