# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0029_auto_20160421_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date_s',
            field=models.DateField(default='01.01.2016', help_text='Дата начала'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='days',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SUN', 'Суббота'), ('SAT', 'Воскресенье')], max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_e',
            field=models.TimeField(default='01:00', help_text='Время конца'),
        ),
    ]
