# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 03:34
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0031_auto_20160421_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='days',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('Дни недели', (('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WEN', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SUN', 'Суббота'), ('SUT', 'Воскресенье')))], max_length=28, null=True),
        ),
    ]
